### ISSUE TITLE
grub.cfg

### ISSUE THREAD

**Issue by Roverworld212** [dreamos82/Dreamos64#85]
// More modules may be added here in the form module path cmdline

Shouldn't it be 'module2'? Since you use multiboot2

edit: format

**Comment by dreamos82** [comment]
well probably you are right :), 
i created that cfg file starting from a template i found on some tutorial. 
So i didn't pay attention to that comment, even because so far i'm not using any module.

Thanks for pointing it out, i will fix it in one of the branch i'm currently working on.

**Comment by Roverworld212** [comment]
It wasn't that big of an issue, but it could make some people confused

**Comment by dreamos82** [comment]
yeah i know, in fact i have a branch now where i'm working on right now, since the update is tiny i will add the change there!
